@baseUrl = http://localhost:3001/api/v1

### Crear un usuario de prueba
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "dev_tester",
  "email": "tester@takent.dev",
  "password": "SecurePassword2024!",
  "firstName": "Carlos",
  "lastName": "Rodríguez",
  "imageUrl": "https://api.dicebear.com/7.x/pixel-art/svg?seed=Carlos"
}

### buscar un usuario por id
GET {{baseUrl}}/users/aee1c7ae-e032-4f4d-98f8-4e2baa615831
Accept: application/json

### actualizar un usuario por id
PATCH {{baseUrl}}/users/aee1c7ae-e032-4f4d-98f8-4e2baa615831
Content-Type: application/json

{
  "username": "userjuan",
  "email": "juan@takent.com",
  "firstName": "Juan"
}

### eliminar un usuario por id
DELETE {{baseUrl}}/users/aee1c7ae-e032-4f4d-98f8-4e2baa615831

### iniciar sesión
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "email": "juan@takent.com",
  "password": "SecurePassword2024!"
}

### registrar un usuario
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "ana_dev",
  "email": "ana@example.com",
  "password": "Password123!",
  "firstName": "Ana",
  "lastName": "García"
}