@baseUrl = http://localhost:3001/api/v1

### Crear un usuario de prueba
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "dev_tester",
  "email": "tester@takent.dev",
  "password": "SecurePassword2024!",
  "firstName": "Carlos",
  "lastName": "Rodríguez",
  "imageUrl": "https://api.dicebear.com/7.x/pixel-art/svg?seed=Carlos"
}

### buscar un usuario por id
GET {{baseUrl}}/users/aee1c7ae-e032-4f4d-98f8-4e2baa615831
Accept: application/json

### actualizar un usuario por id
PATCH {{baseUrl}}/users/aee1c7ae-e032-4f4d-98f8-4e2baa615831
Content-Type: application/json

{
  "username": "userjuan",
  "email": "juan@takent.com",
  "firstName": "Juan"
}

### eliminar un usuario por id
DELETE {{baseUrl}}/users/aee1c7ae-e032-4f4d-98f8-4e2baa615831

### registrar un usuario
POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
  "username": "oskirove",
  "email": "oscar@takent.com",
  "password": "12345678",
  "firstName": "Óscar",
  "lastName": "Rodríguez"
}

### Iniciar sesión
# @name login
POST {{baseUrl}}/auth/sign-in
Content-Type: application/json

{
  "email": "oscar@takent.com",
  "password": "12345678"
}

### Guardamos el token
@access_token = {{login.response.body.accessToken}}

### Probar Ruta Protegida (Perfil)
GET {{baseUrl}}/users/data
Authorization: Bearer {{access_token}}

### Crear un post
POST {{baseUrl}}/posts
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "content": "La era del 'Cloud-Only' está llegando a su fin. 🏠 He migrado toda mi infraestructura crítica de SaaS comerciales a instancias auto-alojadas usando Docker y Coolify. Tener el control total de mis datos y de mi base de datos Postgres no solo me ahorra cientos de dólares al mes, sino que me da una privacidad que ninguna Big Tech puede garantizar. El self-hosting ya no es un hobby, es una necesidad profesional en 2026. 🔐",
  "hashtags": ["SelfHosting", "OpenSource", "Docker", "Privacy", "DevOps"]
}

### Actualizar un post
PATCH {{baseUrl}}/posts/b892a226-ade8-4519-a245-36b754b64572
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "content": "¡El desarrollo de Agentes de IA acaba de cambiar para siempre! 🚀 Acabo de implementar el Model Context Protocol (MCP) en mi flujo de trabajo de Next.js y la capacidad de Claude y GPT-4o para interactuar directamente con mis bases de datos locales y herramientas de terminal es de otro mundo. Se acabó el copiar y pegar logs. ¿Alguien más está integrando agentes autónomos en su pipeline de CI/CD? El futuro no es escribir código, es dirigir a quienes lo escriben. #AI #NextJS #MCP #WebDev"
}

### Eliminar un post
DELETE {{baseUrl}}/posts/2656fc07-ca39-458a-956c-11cbdabb418a
Authorization: Bearer {{access_token}}

### Obtener todos los posts
GET {{baseUrl}}/posts
Authorization: Bearer {{access_token}}

### Obtener los posts de un usuario
GET {{baseUrl}}/posts/user/210d0500-c371-4196-9333-b35802a28163
Authorization: Bearer {{access_token}}


